### ISSUE TITLE
Newest release isn't the latest version

### ISSUE THREAD

**Issue by bhundven** [aquaproj/aqua#2747] opened 2024-03-14 16:38 UTC
### aqua info

```console
$ aqua info
{
  "version": "2.24.1",
  "commit_hash": "86a049eb20113817bf9c6b14c8d201ee780f365f",
  "os": "linux",
  "arch": "amd64",
  "pwd": "/home/(USER)",
  "root_dir": "/home/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_ROOT_DIR": "/home/(USER)/.local/share/aquaproj-aqua"
  },
  "config_files": [
    {
      "path": "/home/(USER)/aqua.yaml"
    }
  ]
}
```

### Overview

Went to update aqua packages, and kubectl downgraded because a new version of 1.26 was released:
```
INFO[0001] updating a package                            aqua_version=2.24.1 env=linux/amd64 new_version=v1.26.15 old_version=v1.29.2 package_name=kubernetes/kubectl program=aqua
```

But I am using a 1.29 cluster.

### How to reproduce

aqua.yaml

```yaml
---
registries:
  - type: standard
    ref: v4.152.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: aquasecurity/trivy@v0.49.1
  - name: cli/cli@v2.45.0
  - name: helm/helm@v3.14.3
  - name: kubernetes-sigs/kind@v0.22.0
  - name: kubernetes/kubectl@v1.29.2
  - name: kubernetes/minikube@v1.32.0
  - name: nektos/act@v0.2.60
  - name: rhysd/actionlint@v1.6.27
```

Other related code such as local Registry

```
$ aqua up
INFO[0001] updating a package                            aqua_version=2.24.1 env=linux/amd64 new_version=v1.26.15 old_version=v1.29.2 package_name=kubernetes/kubectl program=aqua
```

Executed command and output

```console
$ 
No update for kubectl
```

### Debug output

```console
$ 
```

### Expected behaviour

It wouldn't downgrade version because there is a new release of an older version.

### Actual behaviour

What has been explained already.

**Comment by suzuki-shunsuke** [comment] 2024-03-14 22:12
Thank you for your report.

This is because v1.26.15 is the most recently created tag.

https://github.com/kubernetes/kubectl/tags

<img width="418" alt="image" src="https://github.com/aquaproj/aqua/assets/13323303/83cb24b1-d4bf-408e-a153-992ed5ae0ce4">

But we should evaluate versions as semver.

**Comment by suzuki-shunsuke** [comment] 2024-03-14 22:19
Oh, sorry. I'm wrong.

kubernetes/kubectl gets versions from GitHub Releases of https://github.com/kubernetes/kubernetes/releases

https://github.com/aquaproj/aqua-registry/blob/4374864ea6f84762bf394951a5271f8788490e0d/pkgs/kubernetes/kubectl/registry.yaml#L4-L5

And kubernetes v1.26.5 is the latest release.

https://github.com/kubernetes/kubernetes/releases/tag/v1.26.15

That's why kubectl is downgraded to v1.26.15.

**Comment by suzuki-shunsuke** [comment] 2024-03-14 22:20
Duplicate of #2354

**Closed by suzuki-shunsuke** 2024-03-14 22:20 UTC
Labels: bug
