### ISSUE TITLE
Checksum verification of aws/aws-cli fails because the expected checksum of aws/aws-cli is wrong

### ISSUE THREAD

**Issue by nikolay** [aquaproj/aqua#2467] opened 2023-11-14 22:47 UTC
```
$ aws version
INFO[0000] download and unarchive the package            aqua_version=2.17.1 env=darwin/arm64 exe_name=aws package_name=aws/aws-cli package_version=2.13.35 program=aqua registry=standard
FATA[0001] aqua failed                                   actual_checksum=36D16A6156150B3940CD7E750FBD7B9C529EE93C8E0EB594283F19A197DE5C42 aqua_version=2.17.1 env=darwin/arm64 error="install the package: checksum is invalid" exe_name=aws expected_checksum=C42812A6F061D931BB21DC12FE9399E8EDD680DA22704CAA2F4836C538C06621 package_name=aws/aws-cli package_version=2.13.35 program=aqua
```

**Comment by suzuki-shunsuke** [comment] 2023-11-15 00:04
I transferred the issue from aquaproj/aqua-registry to aquaproj/aqua because this is the issue of aqua itself.

**Comment by suzuki-shunsuke** [comment] 2023-11-15 03:29
I could reproduce the issue with the small code.

main.go

```go
package main

import (
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"

	"github.com/codingsince1985/checksum"
)

func main() {
	if err := core(); err != nil {
		log.Fatal(err)
	}
}

func core() error {
	rc, err := download("http://awscli.amazonaws.com/AWSCLIV2-2.13.35.pkg")
	if err != nil {
		return err
	}
	defer rc.Close()
	s, err := checksum.SHA256sumReader(rc)
	if err != nil {
		return err
	}
	fmt.Println(s)
	return nil
}

var (
	errInvalidHTTPStatusCode = errors.New("status code >= 400")
)

func download(u string) (io.ReadCloser, error) {
	client := http.DefaultClient
	req, err := http.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, fmt.Errorf("create a http request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send http request: %w", err)
	}
	if resp.StatusCode >= http.StatusBadRequest {
		return resp.Body, errInvalidHTTPStatusCode
	}
	log.Println("status code:", resp.StatusCode)
	return resp.Body, nil
}
```

The checksum is changed every time.

```console
$ go run .  
2023/11/15 12:25:43 status code: 200
7184789b956d9359e1ac71ebe828470597bd458be918c2e7cac6a5960a512ef8

$ go run .
2023/11/15 12:25:46 status code: 200
e2a81ed5b16c77aa22478e3923c22ea4d3db4668fdfe702aeeb87851b4dd2d84
```

**Comment by suzuki-shunsuke** [comment] 2023-11-15 04:04
The following code resolves the issue.

```go
package main

import (
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"

	"github.com/codingsince1985/checksum"
)

func main() {
	if err := core(); err != nil {
		log.Fatal(err)
	}
}

func core() error {
	path, err := downloadAndCopy()
	if err != nil {
		return err
	}
	defer func() {
		if err := os.Remove(path); err != nil {
			log.Println(err)
		}
	}()

	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	s, err := checksum.SHA256sumReader(f)
	if err != nil {
		return err
	}
	fmt.Println(s)
	return nil
}

func downloadAndCopy() (string, error) {
	rc, err := download("http://awscli.amazonaws.com/AWSCLIV2-2.13.35.pkg")
	if err != nil {
		return "", err
	}
	defer rc.Close()
	f, err := os.CreateTemp("", "")
	if err != nil {
		return "", err
	}
	defer func() {
		f.Close()
	}()
	if _, err := io.Copy(f, rc); err != nil {
		return "", err
	}
	return f.Name(), nil
}

var (
	errInvalidHTTPStatusCode = errors.New("status code >= 400")
)

func download(u string) (io.ReadCloser, error) {
	client := http.DefaultClient
	req, err := http.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, fmt.Errorf("create a http request: %w", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("send http request: %w", err)
	}
	if resp.StatusCode >= http.StatusBadRequest {
		return resp.Body, errInvalidHTTPStatusCode
	}
	log.Println("status code:", resp.StatusCode)
	return resp.Body, nil
}
```

```console
$ go run .  
2023/11/15 13:00:32 status code: 200
36d16a6156150b3940cd7e750fbd7b9c529ee93c8e0eb594283f19a197de5c42

$ go run .  
2023/11/15 13:01:24 status code: 200
36d16a6156150b3940cd7e750fbd7b9c529ee93c8e0eb594283f19a197de5c42
```

I'm not sure why, but it seems that we need to do the following things.

1. Create a temporal file
2. Copy response body to the temporal file
3. Close the response body
4. open the temporal file and calculate the checksum with the reader

**Comment by suzuki-shunsuke** [comment] 2023-11-15 04:13
- https://github.com/aquaproj/aqua/pull/2469

**Closed** 2023-11-15 04:19 UTC
Labels: bug, checksum verification, command:update-checksum

**Comment by suzuki-shunsuke** [comment] 2023-11-15 04:38
v2.17.2 is out 🎉
https://github.com/aquaproj/aqua/releases/tag/v2.17.2

**Comment by suzuki-shunsuke** [comment] 2023-11-15 04:44
If you face the issue already, please remove checksums of aws/aws-cli from aqua-checksums.json and run `aqua update-checksum` with aqua v2.17.2 or newer.

aqua-checksums.json

```json
    // Delete this element
    {
      "id": "http/awscli.amazonaws.com/AWSCLIV2-2.13.35.pkg",
      "checksum": "520E1CB49004ECED7DB1CFE70E6FA73EFC6EDDF1CDB38AF535D126F1DB6574C8",
      "algorithm": "sha256"
    },
```
